### ISSUE TITLE
Question: does Neon used Shared or Copy memory interfacing

### ISSUE THREAD

**Issue by jadbox** [rustbridge/neon#55]
For receiving and sending data from V8 through function invocation, are the parameters copied as well as the return object? I across the below article and thought it might be interesting if Neon support shared memory IO into V8.

http://blog.scottfrees.com/how-not-to-access-node-js-from-c-worker-threads

**Comment by dherman** [comment]
At least for now, the kinds of patterns of parallelism you can use are limited, because the goal is to retain Rust's memory and concurrency safety guarantees, in particular freedom from data races. I have doubts we'd be able to support shared memory IO but I'd certainly be open to learning safe ways of making that work.
